# Makefile for Exercise 14
CXX = /usr/bin/g++
MAIN = exercise_14
FILE = exercise_14.cpp
CXXFLAGS = -Wall

# Type 'make' to create the executable
${MAIN}: ${FILE}
	${CXX} ${CXXFLAGS} $? -o $@
	@echo 'Use ./${MAIN} to run'

# Clean-Up the executable
clean:
	rm -rf ${MAIN}
	
